<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit906e9c118ad72b3a6692b7e764db90b7
{
    public static $prefixLengthsPsr4 = array (
        'T' => 
        array (
            'Twilio\\' => 7,
        ),
        'S' => 
        array (
            'Stripe\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Twilio\\' => 
        array (
            0 => __DIR__ . '/..' . '/twilio/sdk/src/Twilio',
        ),
        'Stripe\\' => 
        array (
            0 => __DIR__ . '/..' . '/stripe/stripe-php/lib',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit906e9c118ad72b3a6692b7e764db90b7::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit906e9c118ad72b3a6692b7e764db90b7::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit906e9c118ad72b3a6692b7e764db90b7::$classMap;

        }, null, ClassLoader::class);
    }
}
